version: '2'

services:
  webapplication:
    image: webapplication
    build:
      context: ./WebApplication
      dockerfile: Dockerfile

  webapplication1:
    image: webapplication
    build:
      context: ./WebApplication
      dockerfile: Dockerfile
